# Generated by Django 5.0.3 on 2024-03-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_client_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=10, verbose_name='State'),
        ),
    ]
